services:
  - type: web
    name: finance-api
    runtime: python
    rootDir: app
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: finance-db
          property: connectionString

databases:
  - name: finance-db
    databaseName: finance_db
    user: finance_user
    plan: free
